//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public int ConferenceId { get; set; }
        public int ProfileId { get; set; }
        public string Content { get; set; }
        public byte[] Image { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Location { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
