//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int msg_id { get; set; }
        public int conv_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime msg_date { get; set; }
        public string msg_txt { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User User { get; set; }
    }
}
